### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ki4arl** [AryanNanda17/NonStop-Lofi-Vibe-Generator#91]
20:52:22 [vite] http proxy error at /api/auth/signup:
Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)

**Comment by ParamThakkar123** [comment]
Thanks for pointing this out. Actually this is not an error with the web app, this is an error that occurs sometimes while using the vite server. Try starting the web app again and see if it works or got to vite.config.js and set the proxy link to run on IPv4 address like instead of `http://localhost:3000` try changing it to `http://127.0.0.1:3000` and see if it works out.

**Comment by ki4arl** [comment]
Hi. Too

`21:39:37 [vite] http proxy error at /api/auth/signup:
Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1278:16)
`

**Comment by ParamThakkar123** [comment]
Did you run the backend code ??

**Comment by ParamThakkar123** [comment]
it's present inside the lofi_backend folder. you need to run it separately and simultaneously with the web app. I think that's the issue

**Comment by ki4arl** [comment]
I didn't know, sorry, try it

**Comment by ki4arl** [comment]
`> lofivitebackend@1.0.0 dev
> nodemon lofiapi/index.js

[nodemon] 3.0.2
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,cjs,json
[nodemon] starting `node lofiapi/index.js`
MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.
    at NativeConnection.createClient (C:\Users\Kirill\Desktop\lofi\NonStop-Lofi-Vibe-Generator\lofi_backend\node_modules\mongoose\lib\drivers\node-mongodb-native\connection.js:206:11)
    at NativeConnection.openUri (C:\Users\Kirill\Desktop\lofi\NonStop-Lofi-Vibe-Generator\lofi_backend\node_modules\mongoose\lib\connection.js:759:34)
    at Mongoose.connect (C:\Users\Kirill\Desktop\lofi\NonStop-Lofi-Vibe-Generator\lofi_backend\node_modules\mongoose\lib\mongoose.js:403:15)
    at file:///C:/Users/Kirill/Desktop/lofi/NonStop-Lofi-Vibe-Generator/lofi_backend/lofiapi/index.js:9:10
    at ModuleJob.run (node:internal/modules/esm/module_job:268:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:543:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:116:5)
(node:23944) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Server on port 3000
`

Error backend


Frontend
`(node:16792) [DEP0060] DeprecationWarning: The `util._extend` API is deprecated. Please use Object.assign() instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
`

**Comment by ki4arl** [comment]
![logs](https://github.com/user-attachments/assets/5373f2e0-9b2a-450d-8887-d0aa5ddb2ad0)

**Comment by ParamThakkar123** [comment]
That's because you didn't add the mongodb database url to the `.env` file.

**Comment by ParamThakkar123** [comment]
Seems like we need to make our setup instructions more elaborative.

**Comment by ki4arl** [comment]
Yes, it would be nice

**Comment by ki4arl** [comment]
Hi! What about updating the instructions?
